// <auto-generated />
using System;
using FlashFortune.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlashFortune.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlashFortune.Domain.Entities.BusinessUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CorporateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstitutionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("BusinessUnits");
                });

            modelBuilder.Entity("FlashFortune.Domain.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("IdentityDoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RaffleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RaffleId", "AccountNumber")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("FlashFortune.Domain.Entities.Prize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RaffleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RaffleId");

                    b.ToTable("Prizes");
                });

            modelBuilder.Entity("FlashFortune.Domain.Entities.Raffle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConversionFactor")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceFileKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TotalCoupons")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitId");

                    b.ToTable("Raffles");
                });

            modelBuilder.Entity("FlashFortune.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FlashFortune.Domain.Entities.UserUnitRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "BusinessUnitId", "Role");

                    b.HasIndex("BusinessUnitId");

                    b.ToTable("UserUnitRoles");
                });

            modelBuilder.Entity("FlashFortune.Domain.Entities.Winner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CouponNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("DrawnAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrizeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RaffleId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("PrizeId");

                    b.HasIndex("RaffleId");

                    b.ToTable("Winners");
                });

            modelBuilder.Entity("FlashFortune.Domain.Entities.Participant", b =>
                {
                    b.HasOne("FlashFortune.Domain.Entities.Raffle", null)
                        .WithMany("Participants")
                        .HasForeignKey("RaffleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FlashFortune.Domain.ValueObjects.CouponRange", "CouponRange", b1 =>
                        {
                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Count")
                                .HasColumnType("bigint")
                                .HasColumnName("coupon_count");

                            b1.Property<long>("VirtualStart")
                                .HasColumnType("bigint")
                                .HasColumnName("coupon_virtual_start");

                            b1.HasKey("ParticipantId");

                            b1.ToTable("Participants");

                            b1.WithOwner()
                                .HasForeignKey("ParticipantId");
                        });

                    b.Navigation("CouponRange")
                        .IsRequired();
                });

            modelBuilder.Entity("FlashFortune.Domain.Entities.Prize", b =>
                {
                    b.HasOne("FlashFortune.Domain.Entities.Raffle", null)
                        .WithMany("Prizes")
                        .HasForeignKey("RaffleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlashFortune.Domain.Entities.Raffle", b =>
                {
                    b.HasOne("FlashFortune.Domain.Entities.BusinessUnit", null)
                        .WithMany("Raffles")
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FlashFortune.Domain.ValueObjects.AuditSeed", "Seed", b1 =>
                        {
                            b1.Property<Guid>("RaffleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FileHash")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("seed_file_hash");

                            b1.Property<string>("RandomComponent")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("seed_random");

                            b1.HasKey("RaffleId");

                            b1.ToTable("Raffles");

                            b1.WithOwner()
                                .HasForeignKey("RaffleId");
                        });

                    b.Navigation("Seed");
                });

            modelBuilder.Entity("FlashFortune.Domain.Entities.UserUnitRole", b =>
                {
                    b.HasOne("FlashFortune.Domain.Entities.BusinessUnit", null)
                        .WithMany()
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashFortune.Domain.Entities.User", null)
                        .WithMany("UnitRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlashFortune.Domain.Entities.Winner", b =>
                {
                    b.HasOne("FlashFortune.Domain.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashFortune.Domain.Entities.Prize", "Prize")
                        .WithMany()
                        .HasForeignKey("PrizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashFortune.Domain.Entities.Raffle", null)
                        .WithMany("Winners")
                        .HasForeignKey("RaffleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Prize");
                });

            modelBuilder.Entity("FlashFortune.Domain.Entities.BusinessUnit", b =>
                {
                    b.Navigation("Raffles");
                });

            modelBuilder.Entity("FlashFortune.Domain.Entities.Raffle", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Prizes");

                    b.Navigation("Winners");
                });

            modelBuilder.Entity("FlashFortune.Domain.Entities.User", b =>
                {
                    b.Navigation("UnitRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
